builds:
  - id: anchore-admission-controller
    main: ./cmd/kubernetes-admission-controller
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X main.version={{ .Env.VERSION }}
      - -X main.gitCommit={{ .Env.COMMIT_HASH }}
      - -X main.buildDate={{ .Env.BUILD_DATE }}
      - -X main.gitDescription=""
