apiVersion: skaffold/v3
kind: Config
build:
  platforms: ["linux/arm64"]
  artifacts:
  - image: skaffold-helm
    ko:
      fromImage: registry.access.redhat.com/ubi8/ubi-minimal:latest
      main: ./cmd/kubernetes-admission-controller
  local:
    push: false
manifests:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: anchore-admission-controller
      valuesFiles:
      - skaffold-values-file.yaml
      namespace: skaffold
      createNamespace: true
      setValues:
        image: skaffold-helm
deploy:
  helm: {}
