apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: skaffold-helm
    ko:
      main: ./cmd/kubernetes-admission-controller
  local:
    push: false
manifests:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: anchore-admission-controller
      valuesFiles:
      - skaffold-values-file.yaml
      namespace: skaffold
      createNamespace: true
      setValues:
        image: skaffold-helm
deploy:
  helm: {}