/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// Response envelope for paginated listing of events
type EventsList struct {

	// List of events
	Results []EventResponse `json:"results,omitempty"`

	// Boolean flag, True indicates there are more events and False otherwise
	NextPage bool `json:"next_page,omitempty"`

	// Number of events in this page
	ItemCount int32 `json:"item_count,omitempty"`

	// Page number of this result set
	Page int32 `json:"page,omitempty"`
}

// A record of occurance of an asynchronous event triggered either by system or by user activity
type EventResponse struct {

	GeneratedUuid string `json:"generated_uuid,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Event *EventResponseEvent `json:"event,omitempty"`
}

type EventResponseEvent struct {

	Source *EventResponseEventSource `json:"source,omitempty"`

	Resource *EventResponseEventResource `json:"resource,omitempty"`

	Type_ string `json:"type,omitempty"`

	Level string `json:"level,omitempty"`

	Message string `json:"message,omitempty"`

	Details *interface{} `json:"details,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`
}

type EventResponseEventResource struct {

	UserId string `json:"user_id,omitempty"`

	Id string `json:"id,omitempty"`

	Type_ string `json:"type,omitempty"`
}

type EventResponseEventSource struct {

	Servicename string `json:"servicename,omitempty"`

	Hostid string `json:"hostid,omitempty"`

	BaseUrl string `json:"base_url,omitempty"`

	RequestId string `json:"request_id,omitempty"`
}

