/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// A record of a software item which is vulnerable or carries a fix for a vulnerability
type PackageReference struct {

	// Package name
	Name string `json:"name,omitempty"`

	// A version for the package. If null, then references all versions
	Version string `json:"version,omitempty"`

	// Package type (e.g. package, rpm, deb, apk, jar, npm, gem, ...)
	Type_ string `json:"type,omitempty"`
}
