name: release

on:
  push:
    # Ignore all branches for release
    branches-ignore:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 #v6.2.0
      with:
        go-version: "1.25.5"

    - name: Test
      run: make test

    - name: Setup Ko
      uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d #v0.9

    - name: Login to Docker Hub
      id: docker-login
      run: |
        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
      env:
        DOCKER_USER: ${{ secrets.ANCHOREINTEGRATIONSWRITE_DH_USERNAME }}
        DOCKER_PASS: ${{ secrets.ANCHOREINTEGRATIONSWRITE_DH_PAT }}

    - name: Release Container
      run: make release
