name: release

on:
  push:
    # Ignore all branches for release
    branches-ignore:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #v6.5.0
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: false

    - name: Test
      run: make test

    - name: Setup Ko
      uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 #v0.10

    - name: Login to Docker Hub
      id: docker-login
      run: |
        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
      env:
        DOCKER_USER: ${{ secrets.ANCHOREINTEGRATIONSWRITE_DH_USERNAME }}
        DOCKER_PASS: ${{ secrets.ANCHOREINTEGRATIONSWRITE_DH_PAT }}

    - name: Release Container
      run: make release
